### ISSUE TITLE
Additional Lucid Recipe Fixes

### ISSUE THREAD

**Issue by foigus** [autopkg/macvfx-recipes#10]
I'd normally do this as a PR, but I have zero way to test whether the changes are positive due to not having any Lucid infrastructure:

- The [url in URLDownloader](https://github.com/autopkg/macvfx-recipes/blob/master/Lucid/Lucid.download.recipe#L26) for Lucid.download.recipe probably should be `https://www.lucidlink.com/download/latest/osx/stable/`.  This redirects to the current installation package
- The [Description](https://github.com/autopkg/macvfx-recipes/blob/master/Lucid/Lucid.munki.recipe#L37-L38) for Lucid.munki.recipe probably should _not_ be the description pulled from MacUpdate for the ["match 3" game "Lucid"](https://www.macupdate.com/app/mac/37810/lucid), although the game has the potential to be more fun than the NAS client :-)

**Comment by macvfx** [comment]
URL changed. Munki recipe description fixed (the other recipe was correct)
